# Utiliza la imagen base de OpenJDK 11
FROM openjdk

# Establece el directorio de trabajo
WORKDIR /app

# Copia el JAR de tu aplicación desde la carpeta target al contenedor
COPY . /app

# Define las variables de entorno
ENV DB_URL="jdbc:mysql://localhost:3306/BaseDatos"
ENV DB_USER="redes"
ENV DB_PASSWORD="redes"

expose 1313

# Comando para ejecutar la aplicación con las variables de entorno
CMD ["java", "-cp", ".","proyecto2.Servidor.MainServidor"]

